#!/bin/bash
# Setup wrouesnel style pbuilder configuration for quick and easy automatic
# builds.

PBUILDER_REPO=$HOME/pbuilder-repo
PBUILDER_HOOKS=$HOME/.pbuilder-hooks

echo "Generating a key for use as signing..."
gpg --gen-key --no-default-keyring --secret-keyring $PBUILDER_REPO/pbuilder-secret.gpg --keyring $PBUILDER_REPO/pbuilder-public.gpg --trustdb-name $PBUILDER_REPO/trustdb.gpg

echo "Installing the new key as a trusted key on the host..."
gpg --import --no-options --no-default-keyring --secret-keyring $PBUILDER_REPO/pbuilder-secret.gpg --keyring $PBUILDER_REPO/pbuilder-public.gpg --trustdb-name $PBUILDER_REPO/trustdb.gpg --export-secret-keys -a | gpg --allow-secret-key-import --import --no-options

echo "Installing $1 as trusted key in apt..."
gpg --import --no-options --no-default-keyring --secret-keyring $PBUILDER_REPO/pbuilder-secret.gpg --keyring $PBUILDER_REPO/pbuilder-public.gpg --trustdb-name $PBUILDER_REPO/trustdb.gpg --export-secret-keys -a | sudo apt-key add -

echo "Making pbuilder repository directory..."
mkdir -p $HOME/pbuilder-repo
cp -r pbuilder-repo/* $PBUILDER_REPO/

echo "Setting up pbuilder hooks..."
mkdir -p $PBUILDER_HOOKS
cp .pbuilder-hooks/* $PBUILDER_HOOKS

echo "Installing .pbuilderrc..."
cp .pbuilderrc $HOME/.pbuilderrc

echo "Your new pbuilder keys are the following:"
gpg --no-default-keyring --secret-keyring $PBUILDER_REPO/pbuilder-secret.gpg --keyring $PBUILDER_REPO/pbuilder-public.gpg --trustdb-name $PBUILDER_REPO/trustdb.gpg --list-keys

read -p "Would you like to install the included .pbuilderrc file? (y/n default NO)" ANSWER
if [[ $ANSWER =~ ^[Yy]$ ]]; then
    echo "Installing to $HOME/.pbuilderrc..."
    if [ -e $HOME/.pbuilderrc ]; then
        echo "Backing up existing .pbuilderrc as .pbuilderrc.$(date +%Y%m%d%H%M%S).bak"
        mv "$HOME/.pbuilderrc" "$HOME/.pbuilderrc.$(date +%Y%m%d%H%M%S).bak"
    fi
    mv ".pbuilderrc" "$HOME/.pbuilderrc"
fi

exit 0
