#!/bin/bash
# Manual priming script for the pbuilder repo.
# Expects to invoke $HOME/.pbuilder-hooks/D10apt-ftparchive
# with a manual argument to force it to build. $1 should be the name
# the build (i.e. precise-amd64)

if [[ $EUID != 0 ]]; then
    echo "Must run as root."
    sudo "$0" "$@"
    exit $?
fi

DIST=$1
ARCH=$2

if [ -z $1 ]; then
	echo "No build result proposed. Attempting auto-select of current environment."
fi

if [ -z "$pbuilder_user" ]; then
	pbuilder_user=$SUDO_USER
	export pbuilder_user
fi
echo "PBuilder User: $pbuilder_user"

if [ -z "$pbuilder_user" ]; then
    fatal "Failed to find a pbuilder username"
fi

declare -x HOME
if ! HOME=$( getent passwd "$pbuilder_user" | cut -d: -f6 ); then
    fatal "Could not find pbuilder_user home directory"
fi

# Get the distribution names
: "${DIST:=$(lsb_release --short --codename)}"
: "${ARCH:=$(dpkg --print-architecture)}"

export PBUILDER_REPO="$HOME/pbuilder/repo"
export PBUILDER_HOOKS="$HOME/pbuilder/hooks"
export PBUILDER_CACHE="$HOME/.cache/pbuilder"
export PBUILDER_GPG="$HOME/pbuilder/repo/gpg"

NAME="$DIST-$ARCH"
export BUILDRESULT="$PBUILDER_CACHE/$NAME/result"

DIST=$DIST ARCH=$ARCH "$PBUILDER_HOOKS/I10apt-ftparchive"